version: "3.8"
services:
  postgres:
    image: postgis/postgis:13-3.3
    restart: unless-stopped
    environment:
      POSTGRES_DB: mgnrega
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema:/schema:ro
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"

  backend:
    build: ../backend
    restart: unless-stopped
    depends_on: [postgres, redis]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mgnrega
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      REDIS_HOST: redis
    ports:
      - "8080:8080"

  frontend:
    build: ../frontend
    restart: unless-stopped
    depends_on: [backend]
    ports:
      - "3000:80"

  etl:
    build: ../etl
    restart: "no"
    depends_on: [postgres]
    environment:
      PG_HOST: postgres
      PG_DB: mgnrega
      PG_USER: postgres
      PG_PASS: postgres
      MGNREGA_API_BASE: "https://api.data.gov.in/resource/<RESOURCE_ID>"
      MGNREGA_API_KEY: ""
    command: ["python","etl.py"]

  nginx:
    image: nginx:stable
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend

volumes:
  pgdata:
